service: serverless-nestjs-api


custom:
  stage:  ${opt:stage, self:provider.stage}
  deploymentBucket: YOUR_DEPLOYMENT_BUCKET_NAME
  serverless-layers:
    layersDeploymentBucket: ${self:custom.deploymentBucket}
  logRetentionInDays:
    development: 14  # stage[development]は14日
    production: 90   # stage[production]は90日
    default: 3       # stageが見つからなかったらこれにfallbackするために設定
  memorySize:
    development: 256   # stage[development]は256M
    production: 512    # stage[production]は512M
    default: 256       # stageが見つからなかったらこれにfallbackするために設定
  prune:
    automatic: true
    number: 3
  apiGatewayTags:
    Stage: ${self:custom.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  profile: default
  stage: development
  timeout: 30
  memorySize: ${self:custom.memorySize.${self:custom.stage}, self:custom.memorySize.default}
  deploymentBucket:
    name: ${self:custom.deploymentBucket}
    serverSideEncryption: AES256
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:custom.stage}, self:custom.logRetentionInDays.default}
  environment:
    STAGE: ${self:custom.stage}
  tags: ${self:custom.apiGatewayTags}

plugins:
  - serverless-offline
  - serverless-layers
  - serverless-tag-api-gateway
  - serverless-prune-plugin

package:
  individually: true
  include:
    - dist/**
  exclude:
    - '**'

functions:
  index:
    handler: dist/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
